# Generated by Django 5.0.3 on 2024-07-13 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_cliente_mascota_medicoveterinario_remove_pet_dueno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.cliente'),
            preserve_default=False,
        ),
    ]
