# Generated by Django 5.0.3 on 2024-08-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_expediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicoveterinario',
            name='password',
            field=models.CharField(default='default_password', max_length=255),
        ),
    ]
